---
abstract: 'The Marriage of Message::Stack & Data::Verifier'
author:
  - 'Cory G Watson, C<< <gphat at cpan.org> >>'
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Manager
no_index:
  directory:
    - inc
    - t
requires:
  Data::Verifier: 0.34
  JSON::Any: 0
  Message::Stack: 0.17
  Message::Stack::Parser: 0.01
  MooseX::Storage: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
